name: Publish RSS feeds to GitHub Pages

on:
  schedule:
    - cron: '0 7 * * 5'
      timezone: 'Europe/Zurich'
  workflow_dispatch:

env:
  CI: true
jobs:
  generate_feed:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
